version: '2'
services:
  ui:
    build: ./ui
    volumes:
      - ./ui:/www/ui
  sass:
    build: ./sass
    volumes:
      - ./sass:/www/static
  nginx:
    build: ./proxy
    volumes_from:
      - ui
      - sass
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
